#!/usr/bin/env bash
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
