#!/bin/bash
# configure Nginx to be running as the nginx user

# stop nginx running
sudo service nginx stop

# set the user to run Nginx as master process
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf

# Configure /etc/nginx/sites-enabled/default to bind Nginx to port 8080
sudo sed -i "s/listen 80;/listen 8080;/" /etc/nginx/sites-enabled/default

# Give /etc/nginx/nginx.conf the permission 644
sudo chmod 644 /etc/nginx/nginx.conf

# change ownership of nginx server directory to nginx user
sudo chown nginx:nginx /etc/nginx -R

# check for service running on port 8080
for pid in $(pidof apache2); do
    sudo kill "$pid"
done
